name: Generate Pac-Man contribution graph

on:
  schedule:
    # roda automaticamente 2x por dia (00:00 e 12:00 UTC)
    - cron: '0 */12 * * *'
  workflow_dispatch: {}
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Generate Pac-Man contribution graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 'pacman' é o jogo que come as contribuições
          games: 'pacman'
          player_style: 'opportunistic'
